# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "nifi-example"
  end
   
   config.vm.provision "shell", 
    inline: "sudo apt-get -y update;
    sudo apt-get install -y wget openjdk-7-jdk git;
    sudo apt-get remove maven*;
    wget http://apache.arvixe.com/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz;
    tar -zxf apache-maven-3.2.5-bin.tar.gz;
    sudo cp -R apache-maven-3.2.5 /usr/local;
    sudo ln -s /usr/local/apache-maven-3.2.5/bin/mvn /usr/bin/mvn;
    rm apache-maven-3.2.5-bin.tar.gz;
    cd /vagrant/;
    mkdir matched;
    mkdir unmatched;
    git clone http://git-wip-us.apache.org/repos/asf/incubator-nifi.git;
    cd incubator-nifi;
    git checkout develop; 
    cd nar-maven-plugin/;
    mvn clean install;
    cd ../nifi && mvn -T C2.0 clean install -DskipTests;
    cd assembly;
    mvn assembly:assembly;
    cp target/nifi-*.tar.gz /vagrant/;
    cd /vagrant/ && tar -xzf nifi-*.tar.gz;
    cd nifi-*-SNAPSHOT;
    bin/nifi.sh start;"
end
